# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'

target 'idyllic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for idyllic

  target 'idyllicTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'idyllic-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for idyllic-tvOS

  target 'idyllic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
